name: "Color Labels Action"
description: "GitHub Action to add some color to issue labels"
author: "Anand Chowdhary <https://github.com/AnandChowdhary>"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "umbrella"
  color: "purple"
